#pragma once

// from glfw3.h
#define JC2D_MOUSE_BUTTON_1 0
#define JC2D_MOUSE_BUTTON_2 1
#define JC2D_MOUSE_BUTTON_3 2
#define JC2D_MOUSE_BUTTON_4 3
#define JC2D_MOUSE_BUTTON_5 4
#define JC2D_MOUSE_BUTTON_6 5
#define JC2D_MOUSE_BUTTON_7 6
#define JC2D_MOUSE_BUTTON_8 7
#define JC2D_MOUSE_BUTTON_LAST JC2D_MOUSE_BUTTON_8
#define JC2D_MOUSE_BUTTON_LEFT JC2D_MOUSE_BUTTON_1
#define JC2D_MOUSE_BUTTON_RIGHT JC2D_MOUSE_BUTTON_2
#define JC2D_MOUSE_BUTTON_MIDDLE JC2D_MOUSE_BUTTON_3